<a href="https://colab.research.google.com/github/veapasichnyk/HomeWorksDataLovesAcademy/blob/main/HW_2_1_%D0%9C%D0%B0%D1%82%D1%80%D0%B8%D1%86%D1%96_%D1%96_%D0%B2%D0%B5%D0%BA%D1%82%D0%BE%D1%80%D0%B8_(%D0%B2%D1%81%D1%82%D1%83%D0%BF_%D0%B4%D0%BE_%D0%BB%D1%96%D0%BD_%D0%B0%D0%BB%D0%B3%D0%B5%D0%B1%D1%80%D0%B8).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [2]:
#Створіть numpy вектор vector розмірністю 10
vector = np.random.rand(10)
print(vector)

[0.88577443 0.68026318 0.55356107 0.49040385 0.79359324 0.34608983
 0.76557096 0.16586069 0.00257371 0.11218181]


In [3]:
matrix = np.array([
    [11, 20, 29],
    [14, 23, 32],
    [17, 26, 35]
])

print(matrix)

[[11 20 29]
 [14 23 32]
 [17 26 35]]


In [4]:
vector.shape, matrix.shape

((10,), (3, 3))


### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [5]:
# Додавання 10 і округлення до 2 знаків
vector = np.round(vector + 10, 2)

print(vector)

[10.89 10.68 10.55 10.49 10.79 10.35 10.77 10.17 10.   10.11]


In [6]:
# Множення на 2
matrix = matrix * 2

print(matrix)

[[22 40 58]
 [28 46 64]
 [34 52 70]]


In [7]:
# Створення нового вектора з квадратами
squared_vector = vector ** 2

print(squared_vector)

[118.5921 114.0624 111.3025 110.0401 116.4241 107.1225 115.9929 103.4289
 100.     102.2121]



### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [8]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [9]:
# Множення матриць
result_matrix = np.dot(A.T, B.T)

print(result_matrix)

[[0.7281 0.2034]
 [0.5202 0.2846]]


In [10]:
#множення матриці на вектор
result_matrix_v = np.dot(result_matrix, C)

print(result_matrix_v)

[[0.2034]
 [0.2846]]


In [11]:
# Множення на матрицю D
result_matrix_m = np.dot(result_matrix, D)

print(result_matrix_m)

[[0.2034 0.7281]
 [0.2846 0.5202]]



### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [12]:
#Транспонування матриці
result_matrix_t = result_matrix.T

print(result_matrix_t)

[[0.7281 0.5202]
 [0.2034 0.2846]]


In [13]:
#Транспонування вектора
vector_t = vector.T

print("vector T:")
print(vector_t)
print("shape:", vector_t.shape)


vector T:
[10.89 10.68 10.55 10.49 10.79 10.35 10.77 10.17 10.   10.11]
shape: (10,)


**Пояснення**

vector не має жодної "другої осі" (shape: (10,)), тому при виклику vector.T — нічого не змінюється.

In [14]:
# Розширення розмірності вектора по осі 1
column_vector = np.expand_dims(vector, axis=1)

print("vector:")
print(vector)
print("shape:", vector.shape)

print("\ncolumn_vector:")
print(column_vector)
print("shape:", column_vector.shape)

vector:
[10.89 10.68 10.55 10.49 10.79 10.35 10.77 10.17 10.   10.11]
shape: (10,)

column_vector:
[[10.89]
 [10.68]
 [10.55]
 [10.49]
 [10.79]
 [10.35]
 [10.77]
 [10.17]
 [10.  ]
 [10.11]]
shape: (10, 1)


**Пояснення**

Ми перетворили наш одновимірний рядок vector (shape: (10,)) на двовимірний стовпчик column_vector (shape: (10, 1)).

In [15]:
# Транспонування
column_vector_t = column_vector.T

# Виведення
print("column_vector:")
print(column_vector)
print("shape:", column_vector.shape)

print("\ntransposed column_vector:")
print(column_vector_t)
print("shape:", column_vector_t.shape)

column_vector:
[[10.89]
 [10.68]
 [10.55]
 [10.49]
 [10.79]
 [10.35]
 [10.77]
 [10.17]
 [10.  ]
 [10.11]]
shape: (10, 1)

transposed column_vector:
[[10.89 10.68 10.55 10.49 10.79 10.35 10.77 10.17 10.   10.11]]
shape: (1, 10)


**Пояснення**

column_vector має форму shape: (10, 1) — стовпчик.

Після транспонування — column_vector_t  має форму shape: (1, 10) — тобто рядковий вектор.

Таким чином, транспонування "перевертає" вектор по діагоналі, перетворюючи стовпчик у рядок.